task_manager/urls.py
from django.urls import path
from .views import (
    index,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskDetailView,
    register_user,
    ToggleAssignToWorkerView
)

urlpatterns = [
    path('register/', register_user, name="register"),
    path("", index, name="index"),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="workers-list"
    ),
    path(
        "workers/<int:pk>/detail/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="tasks-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        ToggleAssignToWorkerView.as_view(),
        name="toggle-task-assign",
    ),

    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-types-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),

    path(
        "positions/",
        PositionListView.as_view(),
        name="positions-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
]

app_name = "task_manager"

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
      <div class="container">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-12 col-md-6 my-auto">
            <div class="copyright text-center text-sm text-white text-lg-start">
              &copy; <a href="https://www.linkedin.com/in/maksymprotsak/" class="font-weight-bold text-white" target="_blank">Maksym Protsak</a>
              Coded By.
            </div>
          </div>
          <div class="col-12 col-md-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://github.com/MaksymProtsak/it-company-task-manager" class="nav-link text-white" target="_blank">Sources</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
<footer class="footer pt-2 mt-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-7 mb-2 text-center">
        <div>
          <ul class="d-flex flex-row justify-content-center nav">
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://github.com/MaksymProtsak" target="_blank">
                <i class="fab fa-github text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="http://www.youtube.com/@maksymprotsak3316" target="_blank">
                <i class="fab fa-youtube text-lg opacity-8"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12">
    <div class="text-center">
      <p class="text-dark my-2 font-weight-normal">
        &copy; <a href="https://www.linkedin.com/in/maksymprotsak/" target="_blank">Maksym Protsak</a> - Coded By.
      </p>
    </div>
  </div>
</footer>

templates/includes/navigation-transparent.html
<!-- Navbar Transparent -->
<nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3  navbar-transparent ">
  <div class="container">
    <a class="navbar-brand  text-white " href="/" rel="tooltip" title="Designed and Coded by Creative Tim"
       data-placement="bottom">
      IT company task manager
    </a>
    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation"
            aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
    </button>
    <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
      <ul class="navbar-nav navbar-nav-hover ms-auto">

        {% if request.user.is_authenticated %}

        <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-6">
          <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
             id="dropdownMenuPages8" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
            Pages
            <img src="{{ ASSETS_ROOT }}/img/down-arrow-white.svg" alt="down-arrow" class="arrow ms-2 d-lg-block d-none">
            <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-2 d-lg-none d-block">
          </a>
          <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
               aria-labelledby="dropdownMenuPages8">
            <div class="d-none d-lg-block">
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                Landing Pages
              </h6>
              <a href="/about-us.html" class="dropdown-item border-radius-md">
                <span>About Us</span>
              </a>
              <a href="/contact-us.html" class="dropdown-item border-radius-md">
                <span>Contact Us</span>
              </a>
              <a href="/author.html" class="dropdown-item border-radius-md">
                <span>Author</span>
              </a>
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                Account
              </h6>
              <a href="/sign-in.html" class="dropdown-item border-radius-md">
                <span>Sign In</span>
              </a>
            </div>
            <div class="d-lg-none">
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                Landing Pages
              </h6>
              <a href="/about-us.html" class="dropdown-item border-radius-md">
                <span>About Us</span>
              </a>
              <a href="/contact-us.html" class="dropdown-item border-radius-md">
                <span>Contact Us</span>
              </a>
              <a href="/author.html" class="dropdown-item border-radius-md">
                <span>Author</span>
              </a>
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                Account
              </h6>
              <a href="/sign-in.html" class="dropdown-item border-radius-md">
                <span>Sign In</span>
              </a>
            </div>
          </div>
        </li>
        {% endif %}

        {% if request.user.is_authenticated %}
        <li class="nav-item ms-lg-auto">
          <a class="nav-link nav-link-icon me-2"
             href="{% url 'logout' %}">
            <i class="fa fa-sign-out me-1"></i>
            <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom"
               title="Sign OUT">Logout</p>
          </a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->

templates/includes/navigation.html
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'task_manager:index' %}" rel="tooltip"
             title="Designed and Coded by Creative Tim" data-placement="bottom">
            Home page
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                  Pages
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                      Landing Pages
                    </h6>
                    <a href="{{ user.get_absolute_url }}" class="dropdown-item border-radius-md">
                      <span>User page: {{ user.get_username }}</span>
                    </a>
                    <a href="{% url 'task_manager:workers-list' %}" class="dropdown-item border-radius-md">
                      <span>Workers</span>
                    </a>
                    <a href="{% url 'task_manager:tasks-list' %}" class="dropdown-item border-radius-md">
                      <span>Tasks</span>
                    </a>
                    <a href="{% url 'task_manager:task-types-list' %}" class="dropdown-item border-radius-md">
                      <span>Task types</span>
                    </a>
                    <a href="{% url 'task_manager:positions-list' %}" class="dropdown-item border-radius-md">
                      <span>Positions</span>
                    </a>
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                      Account
                    </h6>
                    <a href="{% url 'login' %}" class="dropdown-item border-radius-md">
                      <span>Sign In</span>
                    </a>
                  </div>
                  <div class="d-lg-none">
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                      Landing Pages
                    </h6>
                    <a href="{{ user.get_absolute_url }}" class="dropdown-item border-radius-md">
                      <span>User page: {{ user.get_username }}</span>
                    </a>
                    <a href="{% url 'task_manager:workers-list' %}" class="dropdown-item border-radius-md">
                      <span>Workers</span>
                    </a>
                    <a href="{% url 'task_manager:tasks-list' %}" class="dropdown-item border-radius-md">
                      <span>Tasks</span>
                    </a>
                    <a href="{% url 'task_manager:task-types-list' %}" class="dropdown-item border-radius-md">
                      <span>Task types</span>
                    </a>
                    <a href="{% url 'task_manager:positions-list' %}" class="dropdown-item border-radius-md">
                      <span>Positions</span>
                    </a>
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                      Account
                    </h6>
                    <a href="{% url 'login' %}" class="dropdown-item border-radius-md">
                      <span>Sign In</span>
                    </a>
                  </div>
                </div>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="Sign OUT">Logout</p>
                  </a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination d-flex justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number%}" class="page-link"><</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number%}" class="page-link">></a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'task_manager:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:workers-list' %}">All workers</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:tasks-list' %}">All tasks</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:task-types-list' %}">All task types</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:positions-list' %}">All positions</a></li>
</ul>