task_manager/urls.py
from django.urls import path
from .views import (
    index,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskDetailView,
    register_user,
    ToggleAssignToWorkerView
)

urlpatterns = [
    path('register/', register_user, name="register"),
    path("", index, name="index"),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="workers-list"
    ),
    path(
        "workers/<int:pk>/detail/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="tasks-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        ToggleAssignToWorkerView.as_view(),
        name="toggle-task-assign",
    ),

    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-types-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),

    path(
        "positions/",
        PositionListView.as_view(),
        name="positions-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
]

app_name = "task_manager"

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

TASK_PRIORITIES = [
    ("bl", "🔴 Blocker"),
    ("cr", "🟠 Critical"),
    ("mj", "🟡 Major"),
    ("mn", "🟢 Minor"),
    ("tr", "🔵 Trivial")
]


class Position(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.CASCADE, )

    def get_absolute_url(self):
        return reverse("task_manager:worker-detail", kwargs={"pk": self.pk})


class Task(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    deadline = models.DateField(null=True)
    is_completed = models.BooleanField()
    priority = models.CharField(max_length=2, choices=TASK_PRIORITIES)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker, related_name="tasks")

    def __str__(self):
        return self.name

task_manager/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy

from .forms import (
    PositionSearchForm,
    TaskTypeSearchForm,
    TaskForm,
    TaskSearchForm,
    WorkerCreateForm,
    WorkerForm,
    WorkerSearchForm,
    SignUpForm
)
from .models import Worker, Task, TaskType, Position


@login_required
def index(request):
    """View function for the home page of the site."""

    num_workers = Worker.objects.count()
    num_tasks = Task.objects.count()
    num_task_types = TaskType.objects.count()
    num_positions = Position.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "num_task_types": num_task_types,
        "num_positions": num_positions,
        "num_visits": num_visits + 1,
    }

    return render(request, "home/index.html", context=context)


def register_user(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = 'Account created successfully.'
            success = True
        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "registration/register.html", {"form": form, "msg": msg, "success": success})


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    context_object_name = "position_list"
    template_name = "task_manager/position_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        position = self.request.GET.get("position", "")
        context["search_form"] = PositionSearchForm(
            initial={"position": position}
        )
        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)
        if form.is_valid() and form.data.get(key="position") is not None:
            return queryset.filter(
                name__icontains=self.request.GET.get("position")
            )
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:positions-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:positions-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:positions-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_type_list"
    template_name = "task_manager/task_type_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        task_type = self.request.GET.get("task_type", "")
        context["search_form"] = TaskTypeSearchForm(
            initial={"task_type": task_type}
        )
        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()
        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid() and form.data.get(key="task_type") is not None:
            return queryset.filter(
                name__icontains=self.request.GET.get("task_type")
            )
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-types-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-types-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task_manager:task-types-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "task_manager/task_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        task = self.request.GET.get("task", "")
        context["search_form"] = TaskSearchForm(
            initial={"task": task}
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.all().select_related("task_type").prefetch_related("assignees")
        form = TaskSearchForm(self.request.GET)
        if form.is_valid() and form.data.get("task") is not None:
            return queryset.filter(
                name__icontains=self.request.GET.get("task")
            )
        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_manager:tasks-list")


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.all(
    ).select_related("task_type").prefetch_related("assignees__position")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        return reverse_lazy(
            "task_manager:task-detail",
            kwargs={"pk": self.object.id}
        )


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:tasks-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    context_object_name = "worker_list"
    template_name = "task_manager/worker_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        worker = self.request.GET.get("worker", "")
        context["search_form"] = WorkerSearchForm(
            initial={"worker": worker}
        )
        return context

    def get_queryset(self):
        queryset = Worker.objects.all().select_related("position")
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid() and form.data.get(key="worker") is not None:
            return queryset.filter(
                username__icontains=self.request.GET.get("worker")
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.all(
    ).select_related("position").prefetch_related("tasks__task_type")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    success_url = reverse_lazy("task_manager:workers-list")
    form_class = WorkerCreateForm


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerForm
    success_url = reverse_lazy("task_manager:workers-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task_manager:workers-list")


class ToggleAssignToWorkerView(LoginRequiredMixin, generic.View):
    @staticmethod
    def get(request, pk):
        worker = Worker.objects.get(id=request.user.id)
        task = Task.objects.get(id=pk)
        if (
            task in worker.tasks.all()
        ):
            worker.tasks.remove(task)
        else:
            worker.tasks.add(task)
        return HttpResponseRedirect(
            reverse_lazy(
                "task_manager:task-detail", args=[pk]
            )
        )

templates/task_manager/index.html
{% extends "base.html" %}

{% block content %}
  <H1>Task manager home page</H1>
  <p>Welcome to Best task manager ever!</p>
  <h2>Dynamic content</h2>
  <p>The task manager has the following record counts:</p>
  <ul>
    <li><strong>Tasks:</strong> {{ num_tasks }}</li>
    <li><strong>Task types:</strong> {{ num_task_types }}</li>
    <li><strong>Workers:</strong> {{ num_workers }}</li>
    <li><strong>Positions:</strong> {{ num_positions }}</li>
  </ul>

  <p>You have visited this page
    {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}

templates/task_manager/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Positions List{% endblock %}

{% block content %}
  {% include "includes/navigation.html" %}

  <div class="container my-7">
    <div class="row">
      <div class="col-lg-12 col-12 mx-auto">
        <table class="table m-n2">
          <tr>
            <td>
              <h1>
                Positions List:
              </h1>
            </td>
            <td style="width: 300px;">
              <form method="get" action="" class="card bg-white text-black shadow px-3 my-2">
                {{ search_form|crispy }}
            </td>
            <td class="text-lg-end w-0">
              <input type="submit" value="🔍" class="btn btn-secondary ml-1 my-2">
              </form>
            </td>
            <td class="text-lg-end w-0">
              <a href="{% url 'task_manager:position-create' %}" class="btn btn-primary my-2">
                Create
              </a>
            </td>
          </tr>
        </table>
        <div class="card z-index-0 fadeIn3 fadeInBottom">
          <div class="card-body pb-0">
            <section class="pt-2 pb-2 table-responsive" id="count-stats">
              {% if position_list %}
                <table class="table">
                  <tr>
                    <th class="w-5">ID</th>
                    <th>Name</th>
                    <th class="w-0"
                    </th>
                    <th class="w-0"></th>
                  </tr>

                  {% for position in position_list %}
                    <tr>
                      <td>
                        {{ position.id }}
                      </td>
                      <td>
                        {{ position.name }}
                      </td>
                      <td>
                        <a href="{% url 'task_manager:position-update' pk=position.id %}" class="btn btn-info">
                          Update
                        </a>
                      </td>
                      <td>
                        <a href="{% url 'task_manager:position-delete' pk=position.id %}" class="btn btn-danger">
                          Delete
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </table>
              {% else %}
                <p>There are no positions in the task manager.</p>
              {% endif %}
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center py-3 mt-n7">
    {% include "includes/pagination.html" %}
  </div>

{% endblock %}

templates/task_manager/task_detail.html
{% extends "base.html" %}
{% block title %}Detail{% endblock %}
{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container my-7">
    <div class="row">
      <div class="col-lg-12 col-12 mx-auto">
        <table class="table m-n2">
          <tr>
            <td>
              <h1>
                Task detail page:
              </h1>
            </td>
            <td class="text-lg-end">
              {% if user in task.assignees.all %}
                <a href="{% url 'task_manager:toggle-task-assign' pk=task.id %}"
                   class="btn btn-primary link-to-page my-2">
                  Delete me from this task
                </a>
              {% else %}
                <a href="{% url 'task_manager:toggle-task-assign' pk=task.id %}"
                   class="btn btn-success link-to-page my-2">
                  Assign me to this task
                </a>
              {% endif %}
            </td>
            <td class="text-lg-end w-0">
              <a href="{% url 'task_manager:task-delete' pk=task.id %}" class="btn btn-danger link-to-page my-2">Delete
              </a>
            </td>
            <td class="text-lg-end w-0">
              <a href="{% url 'task_manager:task-update' pk=task.id %}" class="btn btn-info link-to-page my-2">
                Update
              </a>
            </td>
          </tr>
        </table>

        <div class="card z-index-0 fadeIn3 fadeInBottom mb-3">
          <div class="card-body pb-0">
            <section class="pt-0 pb-2" id="worker-info">
              <table class="table">
                <tr class="text-center">
                  <th>Name</th>
                  <th>Description</th>
                  <th>Deadline</th>
                  <th>Is completed</th>
                  <th>Priority</th>
                  <th>Task type</th>
                </tr>
                <tr class="text-center">
                  <td class="text-wrap">{{ task.name }}</td>
                  <td class="text-wrap max-width-200">{{ task.description }}</td>
                  <td class="text-center">{{ task.deadline }}</td>
                  <td class="text-center">{{ task.is_completed }}</td>
                  <td class="text-center">{{ task.get_priority_display }}</td>
                  <td class="text-center">{{ task.task_type }}</td>
                </tr>
              </table>
            </section>
          </div>
        </div>

        <div class="ml-3">
          <h4>Assignees:</h4>
          <div class="card z-index-0 fadeIn3 fadeInBottom mt-n1">
            <div class="card-body pb-0">
              <section class="pt-0 pb-2" id="worker-tasks">
                <table class="table">
                  <tr class="text-center">
                    <th>Username</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Is superuser</th>
                    <th>Email</th>
                    <th>Position</th>
                  </tr>
                  {% for assignee in task.assignees.all %}
                    <tr class="text-center">
                      <td>
                        <a href="{% url 'task_manager:worker-detail' pk=assignee.id %}">
                          {{ assignee.username }}
                        </a>
                      </td>
                      <td>{{ assignee.first_name }}</td>
                      <td>{{ assignee.last_name }}</td>
                      <td>{{ assignee.is_superuser }}</td>
                      <td>{{ assignee.email }}</td>
                      <td>{{ assignee.position }}</td>
                    </tr>

                  {% empty %}
                    <p>No assignee(s)!</p>
                  {% endfor %}
                </table>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/task_manager/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}Task List{% endblock %}
{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container my-7">
    <div class="row">
      <div class="col-lg-12 col-12 mx-auto">
        <table class="table m-n2">
          <tr>
            <td>
              <h1>
                Task List:
              </h1>
            </td>
            <td style="width: 300px;">
              <form method="get" action="" class="card bg-white text-black shadow px-3 my-2">
                {{ search_form|crispy }}
            </td>
            <td class="text-lg-end w-0">
              <input type="submit" value="🔍" class="btn btn-secondary ml-1 my-2">
              </form>
            </td>
            <td class="text-lg-end w-0">
              <a href="{% url 'task_manager:task-create' %}" class="btn btn-primary my-2">
                Create
              </a>
            </td>
          </tr>
        </table>
        <div class="card z-index-0 fadeIn3 fadeInBottom">
          <div class="card-body pb-0">
            <section class="pt-2 pb-2 table-responsive" id="count-stats">
              {% if task_list %}
                <table class="table">
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Priority</th>
                    <th>Deadline</th>
                    <th>Is completed</th>
                    <th>Task type</th>
                    <th>Assignees</th>
                    <th class="w-0"></th>
                    <th class="w-0"></th>
                  </tr>

                  {% for task in task_list %}
                    <tr>
                      <td>
                        {{ task.id }}
                      </td>
                      <td>
                        <a href="{% url 'task_manager:task-detail' pk=task.id %}">{{ task.name }}</a>
                      </td>
                      <td>
                        {{ task.get_priority_display }}
                      </td>
                      <td>
                        {{ task.deadline }}
                      </td>
                      <td>
                        {{ task.is_completed }}
                      </td>
                      <td>
                        {{ task.task_type }}
                      </td>
                      <td>
                        {{ task.assignees.count }}
                      </td>
                      <td>
                        <a href="{% url 'task_manager:task-update' pk=task.id %}" class="btn btn-info">
                          Update
                        </a>
                      </td>
                      <td>
                        <a class="btn btn-danger"
                           href="{% url 'task_manager:task-delete' pk=task.id %}">
                          Delete
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </table>
              {% else %}
                No tasks yet.
              {% endif %}
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center py-3 mt-n7">
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/task_manager/task_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Task Type List{% endblock %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container my-7">
    <div class="row">
      <div class="col-lg-12 col-12 mx-auto">
        <table class="table m-n2">
          <tr>
            <td>
              <h1>
                Task type list:
              </h1>
            </td>
            <td style="width: 300px;">
              <form method="get" action="" class="card bg-white text-black shadow px-3 my-2">
                {{ search_form|crispy }}

            </td>
            <td class="text-lg-end w-0">
              <input type="submit" value="🔍" class="btn btn-secondary ml-1 my-2">
              </form>
            </td>
            <td class="text-lg-end w-0">
              <a href="{% url 'task_manager:task-type-create' %}" class="btn btn-primary my-2">
                Create
              </a>
            </td>
          </tr>


        </table>
        <div class="card z-index-0 fadeIn3 fadeInBottom">
          <div class="card-body pb-0">
            <section class="pt-2 pb-2 table-responsive" id="count-stats">
              {% if task_type_list %}
                <table class="table">
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th class="w-0"></th>
                    <th class="w-0"></th>
                  </tr>

                  {% for type in task_type_list %}
                    <tr>
                      <td>
                        {{ type.id }}
                      </td>
                      <td>
                        {{ type.name }}
                      </td>
                      <td>
                        <a href="{% url 'task_manager:task-type-update' pk=type.id %}" class="btn btn-info">
                          Update
                        </a>
                      </td>
                      <td>
                        <a class="btn btn-danger"
                           href="{% url 'task_manager:task-type-delete' pk=type.id %}">
                          Delete
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </table>

              {% else %}
                <p>There are no task types in the task manager.</p>
              {% endif %}
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center py-3 mt-n7">
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/task_manager/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "includes/navigation.html" %}
  <div class="page-header align-items-center min-vh-75">
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
          <div class="card z-index-0 fadeIn3 fadeInBottom">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">
                  Delete worker
                </h4>
              </div>
              <div class="card-body">
                <p class="mb-0 text-center">
                  Do you really want to delete '{{ worker }}'?
                  This worker will be deleted from task manager.
                  All data connected with this worker will be saved.
                </p>
                <form role="form" method="post" action="">
                  {% csrf_token %}
                  <input type="submit" value="Yes" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "base.html" %}
{% block title %}Worker detail{% endblock %}
{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container my-7">
    <div class="row">
      <div class="col-lg-12 col-12 mx-auto">
        <table class="table m-n2">
          <tr>
            <td>
              <h1>
                Worker detail page:
              </h1>
            </td>
            <td class="text-lg-end w-0">
              <a href="{% url 'task_manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page my-2">
                Delete
              </a>
            </td>
            <td class="text-lg-end w-0">
              <a href="{% url 'task_manager:worker-update' pk=worker.id %}" class="btn btn-info link-to-page my-2">
                Update
              </a>
            </td>
          </tr>
        </table>

        <div class="card z-index-0 fadeIn3 fadeInBottom mb-3">
          <div class="card-body pb-0">
            <section class="pt-0 pb-2 table-responsive" id="count-stats">
              <table class="table">
                <tr class="text-center">
                  <th>
                    Username
                  </th>
                  <th>
                    First name
                  </th>
                  <th>
                    Last name
                  </th>
                  <th>
                    Is superuser
                  </th>
                  <th>
                    Email
                  </th>
                  <th>
                    Position
                  </th>
                </tr>
                <tr class="text-center">
                  <td>
                    {{ worker.username }}
                  </td>
                  <td>
                    {{ worker.first_name }}
                  </td>
                  <td>
                    {{ worker.last_name }}
                  </td>
                  <td>
                    {{ worker.is_superuser }}
                  </td>
                  <td>
                    {{ worker.email }}
                  </td>
                  <td>
                    {{ worker.position }}
                  </td>
                </tr>
              </table>
            </section>
          </div>
        </div>

        <div class="ml-3">
          <h4>Tasks assigned by {{ worker.username }}:</h4>
          <div class="card z-index-0 fadeIn3 fadeInBottom mt-n1">
            <div class="card-body pb-0">
              <section class="pt-0 pb-2 table-responsive" id="worker-tasks">
                <table class="table">
                  <tr class="text-center">
                    <th style="width: 5%;">#</th>
                    <th>Title</th>
                    <th>Deadline</th>
                    <th>Is completed</th>
                    <th>Priority</th>
                    <th>Type</th>
                    <th>Task id</th>
                  </tr>
                  {% for task in worker.tasks.all %}
                    <tr>
                      <td class="text-center"> {{ forloop.counter }}</td>

                      <td class="text-center">
                        <a href="{% url 'task_manager:task-detail' pk=task.id %}">
                          {{ task.name }}
                        </a>
                      </td>
                      <td class="text-center">{{ task.deadline }}</td>
                      <td class="text-center">{{ task.is_completed }}</td>
                      <td class="text-center">{{ task.get_priority_display }}</td>
                      <td class="text-center">{{ task.task_type }}</td>
                      <td class="text-center">{{ task.id }}</td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td colspan="8">No tasks!</td>
                    </tr>
                  {% endfor %}
                </table>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}